export default [
  { id: 1, name: "AGUILAR SOTO JOHN PEDRO", house: "DAVID" },
  { id: 2, name: "AGUILAR SOTO RUTH", house: "DAVID" },
  { id: 3, name: "ALCOCER ANTEZANA KAREN", house: "DAVID" },
  { id: 4, name: "BEL TORREZ YESENIA", house: "DAVID" },
  { id: 5, name: "BERNAL VALENCIA MONICA", house: "DAVID" },
  { id: 6, name: "BUSTAMANTE ANABI JACOB", house: "DAVID" },
  { id: 7, name: "CALLEJAS GUTIERREZ CELINA", house: "DAVID" },
  { id: 8, name: "CHOQUE ZOLA MILCA SARAI", house: "DAVID" },
  { id: 9, name: "CLAROS LICIDIO DANIELA", house: "DAVID" },
  { id: 10, name: "DORADO ALAIN", house: "DAVID" },
  { id: 11, name: "DORADO TERRAZAS ELIZABETH", house: "DAVID" },
  { id: 12, name: "SEJAS GRETEL", house: "DAVID" },
  { id: 13, name: "JHONATAN", house: "DAVID" },
  { id: 14, name: "JHULISA", house: "DAVID" },
  { id: 15, name: "JOSUE", house: "DAVID" },
  { id: 16, name: "LEDEZMA ANDREA", house: "DAVID" },
  { id: 17, name: "MAMANI FLORES ESTEFANY", house: "DAVID" },
  { id: 18, name: "MEJIA CEREZO HEIDI", house: "DAVID" },
  { id: 19, name: "MONTOYA QUIROZ PAMELA", house: "DAVID" },
  { id: 20, name: "MOROCHI GILVERT", house: "DAVID" },
  { id: 21, name: "PACO CHOQUE ANDREW DANIEL", house: "DAVID" },
  { id: 22, name: "PACO ESCALANTE DAMARIS", house: "DAVID" },
  { id: 23, name: "ROJAS CRUZ JHANET", house: "DAVID" },
  { id: 24, name: "SOLIS ZULMA", house: "DAVID" },
  { id: 25, name: "VERGARA FERNANDEZ JHOSELYN", house: "DAVID" },
  { id: 26, name: "VIRREIRA MEJIA DEYSI", house: "DAVID" },
  { id: 27, name: "YUCRA RAUL", house: "DAVID" },
  { id: 28, name: "ALAN", house: "GEDEON" },
  { id: 29, name: "ASCUI MEJIA ANAHI", house: "GEDEON" },
  { id: 30, name: "BERNAL VALENCIA LIZ", house: "GEDEON" },
  { id: 31, name: "BUSTAMANTE ANABI ELSA", house: "GEDEON" },
  { id: 32, name: "CHOQUE GUEVARA AIDE TERESA", house: "GEDEON" },
  { id: 33, name: "CHOQUE ROXANA", house: "GEDEON" },
  { id: 34, name: "COPALI MURUCHI RIKY", house: "GEDEON" },
  { id: 35, name: "DIAZ MAMANI ELIZABETH DIANA", house: "GEDEON" },
  { id: 36, name: "DOMINGUEZ JHONATHAN", house: "GEDEON" },
  { id: 37, name: "FUENTES LIZBETH", house: "GEDEON" },
  { id: 38, name: "GUARACHI MITA FABIOLA", house: "GEDEON" },
  { id: 39, name: "JHENY", house: "GEDEON" },
  { id: 40, name: "LAZARTE FLORES LIZBETH", house: "GEDEON" },
  { id: 41, name: "MALDONADO TOLA SEYNER", house: "GEDEON" },
  { id: 42, name: "MAMANI COLLAU ROSMERY", house: "GEDEON" },
  { id: 43, name: "MAMANI VALERO MARIANA", house: "GEDEON" },
  { id: 44, name: "MINERVA", house: "GEDEON" },
  { id: 45, name: "MITMA ILLANES KARINA", house: "GEDEON" },
  { id: 46, name: "PRADO DEYSI", house: "GEDEON" },
  { id: 47, name: "RAMOS ANGELINA", house: "GEDEON" },
  { id: 48, name: "SANDY SOLIZ SHARON", house: "GEDEON" },
  { id: 49, name: "TITICHOQUE GARCIA EVELIN", house: "GEDEON" },
  { id: 50, name: "TOLA CONDO ISAIAS", house: "GEDEON" },
  { id: 51, name: "TORREZ LICIDIO JORGE DANIEL", house: "GEDEON" },
  { id: 52, name: "SALAS VALERIA", house: "GEDEON" },
  { id: 53, name: "VERGARA FERNANDEZ RICARDO", house: "GEDEON" },
  { id: 54, name: "ZURITA SANDOVAL NESTOR", house: "GEDEON" },
  { id: 55, name: "ALBA KEYLA", house: "SALOMON" },
  { id: 56, name: "ANTEZANA AGUILAR NEYBAR", house: "SALOMON" },
  { id: 57, name: "SALAS BELEN ANDREA", house: "SALOMON" },
  { id: 58, name: "BRETÓN JHOSELIN", house: "SALOMON" },
  { id: 59, name: "CARRASCO MACIAS SARAH", house: "SALOMON" },
  { id: 60, name: "CHOQUE GONZALES GABRIELA", house: "SALOMON" },
  { id: 61, name: "CHURA MARIO", house: "SALOMON" },
  { id: 62, name: "COLQUE BAUTISTA JHANETH", house: "SALOMON" },
  { id: 63, name: "ESPINOZA MEJIA NOELIA", house: "SALOMON" },
  { id: 64, name: "FERNANDEZ MAMANI ESTHER RUTH", house: "SALOMON" },
  { id: 65, name: "JACINTO", house: "SALOMON" },
  { id: 66, name: "JAITA FLORES ERIKA VALERIA", house: "SALOMON" },
  { id: 67, name: "JOSSELIN", house: "SALOMON" },
  { id: 68, name: "LENY", house: "SALOMON" },
  { id: 69, name: "MAMANI CHIPANA JESUS", house: "SALOMON" },
  { id: 70, name: "MAMANI SAYVA ANGELICA", house: "SALOMON" },
  { id: 71, name: "MAMANI VALERO SANTIAGO", house: "SALOMON" },
  { id: 72, name: "MEJIA HEREDIA BISMARK", house: "SALOMON" },
  { id: 73, name: "MIRABAL HINOJOSA ZOE", house: "SALOMON" },
  { id: 74, name: "ORDOÑEZ ARROYO PAOLA MICAELA", house: "SALOMON" },
  { id: 75, name: "PICACHURI PERALTA JHOSELYN", house: "SALOMON" },
  { id: 76, name: "SALVATIERRA BEATRIZ", house: "SALOMON" },
  { id: 77, name: "TAPIA LOPEZ DANIEL", house: "SALOMON" },
  { id: 78, name: "TORREZ LICIDIO RUTH JOICE", house: "SALOMON" },
  { id: 79, name: "VASQUEZ KENIA", house: "SALOMON" },
  { id: 80, name: "VILLARROEL TERRAZAS GAHAL", house: "SALOMON" },
  { id: 81, name: "ANABEL", house: "SANSON" },
  { id: 82, name: "APAZA CHOQUE NOEMI", house: "SANSON" },
  { id: 83, name: "APAZA GALEF JOSUE", house: "SANSON" },
  { id: 84, name: "APAZA HUANCA FREDDY", house: "SANSON" },
  { id: 85, name: "ARCANGEL CAMACHO WILLIAMS", house: "SANSON" },
  { id: 86, name: "BERNAL VALENCIA EVELIN", house: "SANSON" },
  { id: 87, name: "BUEN DIA BARRIONUEVO NATALIA", house: "SANSON" },
  { id: 88, name: "CATARI VILLARROEL ROSALINDA", house: "SANSON" },
  { id: 89, name: "CHOQUE G FLOR KESTIN", house: "SANSON" },
  { id: 90, name: "DAMARIS", house: "SANSON" },
  { id: 91, name: "FERNANDEZ MAMANI YESENIA", house: "SANSON" },
  { id: 92, name: "GUTIERREZ ALVAREZ BIRGUIT", house: "SANSON" },
  { id: 93, name: "HEREDIA QUISPE JJHAQUELIN DAYANA", house: "SANSON" },
  { id: 94, name: "LOPEZ GONGORA INGHER", house: "SANSON" },
  { id: 95, name: "MAMANI SOLIZ JHOSELYN", house: "SANSON" },
  { id: 96, name: "MAMANI VALERO SILVANA", house: "SANSON" },
  { id: 97, name: "MARCO", house: "SANSON" },
  { id: 98, name: "MEJIA CEREZO LUIS BEYMAR", house: "SANSON" },
  { id: 99, name: "MONTOYA QUIROZ SARAHI", house: "SANSON" },
  { id: 100, name: "JIMENEZ NASHELY", house: "SANSON" },
  { id: 101, name: "ROCHA RIOS ELENA", house: "SANSON" },
  { id: 102, name: "SANCHEZ ROCHA JASMIN ANDREA", house: "SANSON" },
  { id: 103, name: "MERINO CAROLINA", house: "SANSON" },
  { id: 104, name: "SOLIZ LAZARTE ARLET WANDA", house: "SANSON" },
  { id: 105, name: "SUASNABAR ENOC", house: "SANSON" },
  { id: 106, name: "VARGAS ARCE ALEJANDRO JHAMIL", house: "SANSON" },
  { id: 107, name: "VIRACOCHEA GIL JHOAN", house: "SANSON" },
];
